[2023-12-02 15:54:25,298] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:38.815193+00:00 [queued]>
[2023-12-02 15:54:25,426] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:38.815193+00:00 [queued]>
[2023-12-02 15:54:25,428] {{taskinstance.py:880}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 15:54:25,429] {{taskinstance.py:881}} INFO - Starting attempt 1 of 1
[2023-12-02 15:54:25,431] {{taskinstance.py:882}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 15:54:25,459] {{taskinstance.py:901}} INFO - Executing <Task(PythonOperator): load_data_psql> on 2023-12-02T15:52:38.815193+00:00
[2023-12-02 15:54:25,467] {{standard_task_runner.py:54}} INFO - Started process 228 to run task
[2023-12-02 15:54:25,561] {{standard_task_runner.py:77}} INFO - Running: ['airflow', 'run', 'hw-3.4', 'load_data_psql', '2023-12-02T15:52:38.815193+00:00', '--job_id', '8', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/hw-3.4.py', '--cfg_path', '/tmp/tmpmq_4e_fc']
[2023-12-02 15:54:25,563] {{standard_task_runner.py:78}} INFO - Job 8: Subtask load_data_psql
[2023-12-02 15:54:25,634] {{logging_mixin.py:120}} INFO - Running <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:38.815193+00:00 [running]> on host 2cf373442eb7
[2023-12-02 15:54:25,671] {{base_hook.py:89}} INFO - Using connection to: id: conn1. Host: host.docker.internal, Port: 5434, Schema: quotes, Login: postgres, Password: XXXXXXXX, extra: None
[2023-12-02 15:54:25,702] {{taskinstance.py:1150}} ERROR - Ошибка записи данных: name 'print_supported_currencies' is not defined
Traceback (most recent call last):
  File "/usr/local/airflow/dags/modules/functions.py", line 53, in load_data_psql
    response = print_supported_currencies()
NameError: name 'print_supported_currencies' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/modules/functions.py", line 76, in load_data_psql
    raise Exception(f'Ошибка записи данных: {error}')
Exception: Ошибка записи данных: name 'print_supported_currencies' is not defined
[2023-12-02 15:54:25,712] {{taskinstance.py:1194}} INFO - Marking task as FAILED. dag_id=hw-3.4, task_id=load_data_psql, execution_date=20231202T155238, start_date=20231202T155425, end_date=20231202T155425
[2023-12-02 15:54:30,234] {{local_task_job.py:102}} INFO - Task exited with return code 1
